### ISSUE TITLE
PLIP dataset reconstruction.

### ISSUE THREAD

**Issue by trinhvg** [MAGIC-AI4Med/KEP#3]
Dear author, 

In your paper, you use the OpenPath dataset. Please give us some guidance on how you reconstruct the dataset. Since the Openpath only provides us with Twit ID, how can we retrieve the image+twit caption and clean them?

Thank you so much, any instruction is highly appreciated.
Trinh

**Comment by Astaxanthin** [comment]
> Dear author,
> 
> In your paper, you use the OpenPath dataset. Please give us some guidance on how you reconstruct the dataset. Since the Openpath only provides us with Twit ID, how can we retrieve the image+twit caption and clean them?
> 
> Thank you so much, any instruction is highly appreciated. Trinh

Thanks for your interest. PLIP provides the Twitter links of each image-text pair in the "dataframe_208K_rows.csv" file on the website https://drive.google.com/drive/folders/1DfyqngM9WG1gwsm9NAJ5VUgj57UfGaDS. We crawled the image and corresponding Tweet from each Twitter link, and cleaned these pair data according to the section "Quality control of the training dataset" in PLIP paper.

**Comment by trinhvg** [comment]
Thank you!
